@startuml
title User story 1: Start design
actor bruger


boundary designcarport.jsp
boundary orderoverview.jsp
control FrontController

autonumber

bruger -> designcarport.jsp: start
designcarport.jsp -> FrontController: doPost()
FrontController -> FrontController: processRequest()
FrontController -> Command: fromPath()
Command --> FrontController: OrderNew
FrontController -> OrderNew: execute()
OrderNew --> FrontController: orderoverview
FrontController --> orderoverview.jsp: forward()
@enduml